version: '3'


networks:
  redis-net:
    driver: bridge

services:
  redis-1:
    image: redis
    container_name: redis-1
    networks:
      - redis-net
    hostname: redis-1
    ports:
      - 7000:7000
    volumes:
      - ./7000/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-2:
    image: redis
    container_name: redis-2
    networks:
      - redis-net
    hostname: redis-2
    ports:
      - 7001:7001
    volumes:
      - ./7001/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-3:
    image: redis
    container_name: redis-3
    networks:
      - redis-net
    hostname: redis-3
    ports:
      - 7002:7002
    volumes:
      - ./7002/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-4:
    image: redis
    container_name: redis-4
    networks:
      - redis-net
    hostname: redis-4
    ports:
      - 7003:7003
    volumes:
      - ./7003/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-5:
    image: redis
    container_name: redis-5
    networks:
      - redis-net
    hostname: redis-5
    ports:
      - 7004:7004
    volumes:
      - ./7004/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6:
    image: redis
    container_name: redis-6
    networks:
      - redis-net
    hostname: redis-6
    ports:
      - 7005:7005
    volumes:
      - ./7005/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-creator:
    image: redis:latest
    ports:
      - 6999:6999
    networks:
      - redis-net
    command: redis-cli -p 7000 --cluster create redis-1:7000 redis-2:7001 redis-3:7002 redis-4:7003 redis-5:7004 redis-6:7005 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

  redis-insight:
    image: redislabs/redisinsight
    container_name: redis-insight
    networks:
      - redis-net
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis-cluster-creator
